### ISSUE TITLE
大佬你好，最近发现在设置中无法打开设置，一直在转圈

### ISSUE THREAD

**Issue by Char1ieBrown** [bytebeats/mns#117]
![微信截图_20211227135326](https://user-images.githubusercontent.com/31402574/147439186-e80ed59f-4339-4900-9372-94378c1f0821.png)
如图所示，不清楚是哪里出现了问题

**Comment by Char1ieBrown** [comment]
大佬是使用pycharm2021.3不能使用，出现这样的情况，但是我在使用idea2021.1能使用，不知道是不是版本的原因导致的。

**Comment by bytebeats** [comment]
其余两个插件能打开吗?

**Comment by Char1ieBrown** [comment]
pycharm 2021.3不能打开设置，就像上图一样，但是在IntelliJ IDEA 2021.1.1中確可以打开。

**Comment by bytebeats** [comment]
可能跟新版本的 sdk 发生变更有关, 我查看一下.

**Comment by Char1ieBrown** [comment]
感谢大佬

**Comment by Char1ieBrown** [comment]
![image](https://user-images.githubusercontent.com/31402574/147440904-f5228d0b-9122-4226-a9be-de0477712a06.png)


java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at me.bytebeats.mns.handler.AbsStockHandler.convert2Data(AbsStockHandler.java:94)
	at me.bytebeats.mns.handler.AbstractHandler.lambda$updateView$0(AbstractHandler.java:57)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
